apiVersion: apps/v1
kind: Deployment
metadata:
  name: onm-auth-deploy
  namespace: onm-dev
  labels:
    app: onm-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onm-auth
  template:
    metadata:
      labels:
        app: onm-auth
    spec:
      containers:
      - name: onm-auth
        image: feet312/onm-auth  # on server
#        image: onm-auth
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: onm-auth-service
  namespace: onm-dev
spec:
  # type: NodePort
  selector:
    app: onm-auth
  ports:
    - protocol: TCP
      port: 28000
      targetPort: http
      # nodePort: 32180
---