####################
### dev 
####################

server:
  port: 28000


#appinfo
app-info: 
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
    
#actuator
management: 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
